version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"